FROM andrejreznik/python-gdal:py3.7.3-gdal3.0.0
ENV PATH /usr/local/bin:$PATH

RUN echo "deb http://ftp.debian.org/debian stretch-backports main"  > /etc/apt/sources.list.d/backports.list
RUN apt-get update && apt-get install -y unzip build-essential wget virtualenv libspatialindex-dev python-rtree git osmium-tool htop jq parallel curl lsb-release apt-transport-https software-properties-common 
RUN apt -t stretch-backports install osmium-tool
RUN wget -c https://github.com/cli/cli/releases/download/v1.5.0/gh_1.5.0_linux_amd64.deb  && dpkg -i gh_1.5.0_linux_amd64.deb && rm gh_1.5.0_linux_amd64.deb
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - 
RUN apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && apt-get update &&  apt-get install terraform
RUN pip install --upgrade pip